Repository Remynfv/LegitSlimePaper, pull requests merged in 2025-07, with the labels that each got.

#22 Add permission node to allow f3+I
  gradle/wrapper/gradle-wrapper.properties
  legitslimepaper-server/aspaper-patches/files/src/main/java/com/infernalsuite/asp/SlimeNMSBridgeImpl.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  legitslimepaper-server/paper-patches/files/src/main/java/org/bukkit/craftbukkit/util/permissions/CraftDefaultPermissions.java.patch
Labels: bug, enhancement

#23 1.21.7
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  legitslimepaper-api/build.gradle.kts.patch
  legitslimepaper-server/build.gradle.kts.patch
  legitslimepaper-server/minecraft-patches/sources/com/mojang/brigadier/tree/CommandNode.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/commands/Commands.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/commands/functions/MacroFunction.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/network/chat/Style.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/resources/RegistryDataLoader.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/Main.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/commands/ExecuteCommand.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/commands/ReturnCommand.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/commands/TickCommand.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/commands/data/EntityDataAccessor.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/level/ServerChunkCache.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/world/entity/player/Player.java.patch
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/world/level/ServerExplosion.java.patch
  legitslimepaper-server/paper-patches/files/src/main/java/org/bukkit/craftbukkit/Main.java.patch
  legitslimepaper-server/paper-patches/files/src/main/java/org/bukkit/craftbukkit/util/permissions/CraftDefaultPermissions.java.patch
Labels: enhancement

#24 fix: fixed commandapi requirements not working
  legitslimepaper-server/minecraft-patches/sources/net/minecraft/commands/Commands.java.patch
Labels: bug

#27 feat: 1.21.8
  gradle.properties
  legitslimepaper-server/build.gradle.kts.patch
Labels: bug, enhancement
